version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./container/api/Dockerfile
    # portを9000にする。Nginxとの兼ね合い
    ports:
      - "8000:8000" # このPORTとNginx Proxy Managerの「Dashboard > Proxy Host > Add Proxy Host」の Forwad portを合わせる
    volumes:
      - ./backend:/var/www/app
    working_dir: /var/www/app
    command: php artisan serve --host 0.0.0.0
    tty: true
    restart: always
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7
    container_name: real_estimate_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: real_estimate
      MYSQL_USER: koHeiEstimate
      MYSQL_PASSWORD: tc!mGY&5%98
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./container/mysql/data:/var/lib/mysql
      - ./container/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./container/mysql/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"

  # phpMyAdmin
  phpmyadmin:
    container_name: real_estimate_phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=real_estimate_db
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - "8080:80"

  node:
    build:
      context: .
      dockerfile: container/front/Dockerfile
    volumes:
      - ./src:/var/www/application
    tty: true
    command: sh ./start.sh
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
      - '24678:24678' # 追加
    networks:
      - front

networks:
  front: # docker network create front
    external: true

