version: "3"
services:
  node:
    build:
      context: .
      dockerfile: container/front/Dockerfile
    volumes:
      - ./src:/var/www/application
    tty: true
    command: sh ./start.sh
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - '3000:3000'
      - '24678:24678' # 追加
    networks:
      - front
networks:
  front: # docker network create front
    external: true
